credentials:
  usernames:
    admin:
      email: admin@crtest.com
      name: Admin
      password: $2b$12$IJn4HfnN6yJpwuaTQpIlH.P0lHSof8qaQk.gmZK/UiSIChVzKx.mS # To be replaced with hashed password
    user:
      email: user@crtest.com
      name: User
      password: $2b$12$i98eHjVYxAmV9rOqirQcvuh/MPRz1UeOI1rZqb.xofRQ.98Wi0Ouu # To be replaced with hashed password
cookie:
  expiry_days: 10
  key: some_signature_key # Must be string
  name: cr-test-llm
preauthorized:
  emails:
  - admin@crtest.com